// Read-along transcripts shown on the page (collapsible per part).
// Keyed by set id (must match the `id` values in index.html's `sets`).
// These mirror the practice lines spoken in each generator — the "Welcome..."
// intro and the twice-repeated words are trimmed so the text is easy to read.
//
// Plain global (not an ES module) so index.html can load it with a normal
// <script src> tag and it works even when the page is opened as a file:// URL.
window.TRANSCRIPTS = {
  reductions: [
    "I wanna go home.",
    "Do you wanna join us?",
    "She’s gonna call later.",
    "It’s gonna rain.",
    "I gotta finish this today.",
    "You gotta see this.",
    "I hafta leave early.",
    "We hafta try again.",
    "I’m kinda tired.",
    "That’s kinda weird.",
    "I sorta agree.",
    "It’s sorta broken.",
    "Lemme check.",
    "Lemme know.",
    "Gimme a minute.",
    "Gimme that book.",
    "I dunno what happened.",
    "Dunno if it works.",
    "We’re outta time.",
    "He walked outta the room.",
    "I shoulda called.",
    "They coulda won.",
    "He woulda helped.",
    "I ain’t ready.",
    "She ain’t here.",
    "I gotta deploy the server.",
    "We’re gonna refactor the code.",
    "You gotta check the logs.",
    "I wanna merge this branch.",
    "I wanna transfer some money.",
    "I gotta pay off the loan.",
    "They’re gonna review my account.",
    "I hafta update my PIN.",
    "I'm tired 'cuz I worked late.",
    "Whatcha doing?",
    "There's a lotta work.",
    "I'm supposed to finish today.",
    "I used to live here.",
    "She's trying to help.",
    "He has to go now.",
  ],
  "word-reductions": [
    "I need to go now.",
    "This one is for you.",
    "Bread and butter.",
    "I want a cup of coffee.",
    "How are you doing today?",
    "What is your name?",
    "I should have called her.",
    "Can you give them to me?",
    "Tell him I said hi.",
    "Is he coming with us?",
    "He was at the door.",
    "I am from New York.",
    "Do you want coffee or tea?",
    "I would do it again.",
    "Wait for a minute.",
    "As soon as possible.",
    "Push the code to the server.",
    "This update is for the app.",
    "Save and deploy it.",
    "Connect to the database.",
    "Send the money to the bank.",
    "This form is for the loan.",
    "Deposit and withdraw.",
    "Log in to your account.",
    "Fish and chips.",
    "A cup of tea.",
    "Nice to meet you.",
    "Thanks for coming.",
    "A piece of cake.",
    "Rock and roll.",
    "I'll see you at lunch.",
  ],
  contractions: [
    "I. I've. I'll.",
    "I call you. / I've called you. / I'll call you.",
    "You. You've. You'll.",
    "You see it. / You've seen it. / You'll see it.",
    "We. We've. We'll.",
    "We do it. / We've done it. / We'll do it.",
    "They. They've. They'll.",
    "They win. / They've won. / They'll win.",
    "I've deployed the update.",
    "I'll restart the server.",
    "We've fixed the bug.",
    "You'll get a notification.",
    "You've reached your limit.",
    "We'll process your payment.",
    "I've opened an account.",
    "They'll approve the loan.",
    "He's at work.",
    "She's almost done.",
    "It's ready now.",
    "That's mine.",
    "I'd go if I could.",
    "We're on our way.",
    "There's a problem.",
  ],
  "flap-t": [
    "Water.", "Better.", "Butter.", "City.", "Party.", "Computer.", "Pretty.",
    "Metadata.", "Get away.", "What about it?", "A lot of it.", "Put it on.",
    "I gotta go.", "Data.", "Router.", "Editor.", "Latency.", "Update it.",
    "Credit.", "Debit.", "Auditor.", "Pay the quarter.", "Functionality.",
    "Competitor.", "Daughter.", "Ability.", "Automation.", "Thirty.", "Forty.",
    "Little.", "Bottle.", "Letter.", "Beautiful.", "Whatever.", "Get over it.",
  ],
  "glottal-t": [
    "Button.", "Cotton.", "Kitten.", "Written.", "Rotten.", "Gotten.",
    "Bitten.", "Forgotten.", "I didn't.", "I couldn't.", "Mountain.",
    "Certain.", "Curtain.", "Fountain.", "Important.", "Tighten.", "Threaten.",
    "Frighten.", "Shorten.", "Sweeten.", "Mitten.",
    "Click the button.", "It's written in code.", "I've forgotten my password.",
    "Press the button to pay.", "A written statement.", "Forgotten your PIN?",
  ],
  "nt-drop": [
    "I found it on the internet.",
    "Can I get an interview?",
    "That's really interesting.",
    "There were twenty of them.",
    "Meet me in the center.",
    "It's cold in the winter.",
    "Please enter your name.",
    "We have plenty of time.",
    "The printer is broken.",
    "He's a really good hunter.",
    "I live in the county.",
    "I have to see the dentist.",
    "My grandpa is seventy.",
    "I wanted to call you.",
    "Connect to the internet.",
    "Enter your username.",
    "The counter keeps counting.",
    "Check the interest rate.",
    "I have twenty in my account.",
    "Visit the banking center.",
    "It's an international company.",
    "I'm a little disappointed.",
    "What's the quantity?",
    "Twenty twenty.",
    "I had a phone interview.",
  ],
  linking: [
    "An apple.", "Pick it up.", "Turn it off.", "Come on in.", "Go away.",
    "Do it.", "Who is it?", "She is here.", "I agree.", "Be honest.",
    "Bus stop.", "Gas station.", "Bad day.", "Catch up.", "Back it up.",
    "Set it up.", "Log in.", "Check it out.", "Fill it out.", "Pay it off.",
    "Sign in.", "Cash it out.", "An hour.", "Not at all.", "Far away.",
    "First of all.", "Hold on.", "Come on.",
  ],
  palatalization: [
    "What did you eat for breakfast?",
    "Where did you go last night?",
    "Would you help me with this?",
    "Could you call me later?",
    "How did your day go?",
    "I got you a present.",
    "Don't you want some?",
    "Can't you see it?",
    "I bet you can do it.",
    "Nice to meet you.",
    "I'll let you know.",
    "Did you deploy it?",
    "Would you review my code?",
    "Could you restart the server?",
    "Did you get your statement?",
    "Would you like to transfer?",
    "I bet you saved money.",
    "I'll miss you.",
    "God bless you.",
    "How's your day?",
    "What do you think?",
    "Don't you dare.",
  ],
  "minimal-pairs": [
    "world / word / would",
    "World — The whole world is watching.",
    "Word — Say every single word.",
    "Would — I would help you.",
    "walk / work",
    "Walk — Let's go for a walk.",
    "Work — I have a lot of work.",
    "thirty / dirty / thirsty",
    "Thirty — I have thirty dollars.",
    "Dirty — My shoes are dirty.",
    "Thirsty — I am really thirsty.",
    "ship / sheep",
    "Ship — The ship is leaving.",
    "Sheep — Count the sheep.",
    "full / fool",
    "Full — The glass is full.",
    "Fool — Don't be a fool.",
    "bit / beat (IT)",
    "Bit — Flip the bit.",
    "Beat — Don't miss a beat.",
    "cache / cash (homophones!)",
    "Cache — Clear the cache.",
    "Cash — Pay with cash.",
    "bank / bang",
    "Bank — Go to the bank.",
    "Bang — The door shut with a bang.",
    "three / tree (th vs t)",
    "Three — I have three.",
    "Tree — Climb the tree.",
    "live / leave (short i vs long ee)",
    "Live — I live here.",
    "Leave — Don't leave.",
    "pull / pool",
    "Pull — Pull the door.",
    "Pool — Swim in the pool.",
  ],
  "it-acronyms": [
    "XML. The file is in XML format.",
    "SQL. Write a SQL query.",
    "API. Call the API.",
    "URL. Copy the URL.",
    "JSON. Return a JSON response.",
    "HTTP. Send an HTTP request.",
    "CSS. Style it with CSS.",
    "GUI. Open the GUI.",
    "SDK. Install the SDK.",
    "CLI. Run it from the CLI.",
    "UUID. Generate a UUID.",
    "CI CD. Set up the CI CD pipeline.",
    "GIF. Send me a GIF.",
    "SaaS. It's a SaaS product.",
    "Regex. Write a regex.",
    "Nginx. Configure nginx.",
    "Kubernetes. Deploy on Kubernetes.",
    "OAuth. Log in with OAuth.",
    "Enum. Define an enum.",
    "Cache. Clear the cache.",
  ],
  "pilot-comms": [
    "Ladies and gentlemen, this is your captain speaking.",
    "We are now cruising at an altitude of tree fife thousand feet.",
    "Cabin crew, prepare for departure.",
    "Tower, Speedbird niner two, ready for departure, runway two seven.",
    "Speedbird niner two, cleared for takeoff, runway two seven.",
    "Cleared for takeoff, runway two seven, Speedbird niner two.",
    "Center, Delta four fife seven, request descent to flight level tree tree zero.",
    "Delta four fife seven, descend and maintain flight level tree tree zero.",
    "Roger, wilco.",
    "Affirmative.",
    "Standby.",
    "Approach, Delta four fife seven, established on the I.L.S. runway two seven.",
    "Delta four fife seven, cleared to land, runway two seven, wind two fife zero at one zero.",
    "Cabin crew, prepare for landing.",
    "Mayday, mayday, mayday. Delta four fife seven, engine failure, requesting immediate return.",
    "Squawk seven seven zero zero.",
  ],
  "bbc-news": [
    "Good evening, and welcome to the BBC News at Ten.",
    "Our top story tonight.",
    "The Prime Minister has announced a new set of measures this afternoon.",
    "Speaking outside Downing Street, she said the changes would take effect next month.",
    "Our political correspondent has more.",
    "We can now go live to our reporter at the scene.",
    "Thank you. Yes, the situation here is developing quickly.",
    "In other news, markets across Europe closed higher today.",
    "And now, the weather.",
    "Tomorrow will be cloudy, with a chance of rain in the north and brighter spells in the south.",
    "Temperatures will reach a high of fifteen degrees.",
    "That is all from us tonight. From everyone here at the BBC, goodnight.",
    "You're watching BBC World News.",
    "Stay with us. After the break, sport and the headlines.",
  ],
  numbers: [
    "There are 25 students in the class.",
    "The population is about 1,000,000.",
    "The company made 2.5 billion dollars.",
    "Pi is about 3.14.",
    "Add one half cup of sugar.",
    "About three quarters of the team agreed.",
    "It costs $19.99.",
    "The total is $1,250.",
    "Sales rose by 15% this year.",
    "She finished in 1st place.",
    "It's my 21st birthday.",
    "Take the elevator to the 3rd floor.",
    "1500 can be said two ways: fifteen hundred, or one thousand five hundred.",
    "A phone number, 555-0123, is said digit by digit: five five five, oh one two three.",
    "Today it's -5 degrees.",
    "The score was 3 to 2.",
  ],
  dates: [
    "Today is Monday, the 6th of June.",
    "We usually meet on Tuesdays.",
    "My birthday is March 5th.",
    "In Britain we say the 5th of March.",
    "The date 3/5/2024 is read March fifth, twenty twenty-four.",
    "I was born in 1990.",
    "It happened in 2008.",
    "The year 2000 is said two thousand.",
    "By 2025, things had changed.",
    "The train leaves at 9:00 AM.",
    "It's 7:15.",
    "Seven fifteen can also be quarter past seven.",
    "Let's meet at 7:30.",
    "Seven thirty can also be half past seven.",
    "It's 8:45.",
    "Let's have lunch at noon.",
    "The flight departs at 14:30.",
    "The meeting is on June 6th, 2026, at 8 PM.",
  ],
  "radio-tactical": [
    "Command, this is Alpha One, requesting permission to engage, over.",
    "Enemy contact, two hundred meters, north ridge.",
    "We are pinned down, requesting immediate backup, over.",
    "Roger that, reinforcements inbound, hold your position.",
    "Move, move, move!",
    "Take cover! Incoming!",
    "Grenade! Get down!",
    "Man down! We need a medic!",
    "Target neutralized, area secure.",
    "Watch your six!",
    "Air support is on the way, danger close.",
    "Copy that, moving to the extraction point.",
    "Hold the line, do not fall back.",
    "Mission accomplished, returning to base.",
    "Say again, you're breaking up, over.",
    "Wilco. Out.",
  ],
};

// The "radio static" / FX variants reuse the same words as their clean source.
window.TRANSCRIPTS["pilot-radio"] = window.TRANSCRIPTS["pilot-comms"];
window.TRANSCRIPTS["radio-tactical-fx"] = window.TRANSCRIPTS["radio-tactical"];
